### ISSUE TITLE
Crash on start with UndergroundBiomes

### ISSUE THREAD

**Issue by LemADEC** [CyclopsMC/CyclopsCore#115]
#### Issue type:

- :bug: Bug

____

#### Short description:

Crash on game start when adding Dark Gem ore to UndergroundBiomes

#### Steps to reproduce the problem:

1. add dark_ore to the underground biomes configuration:
```
[
  {
    "internalOreName": "evilcraft:dark_ore",
    "meta": -1,
    "overlay": "spectracraft:overlays/gem_black",
    "lightValue": -1,
    "oreDirectories": []
  }
]
```
2. start the game

#### Expected behaviour:

No crash
____

#### Versions:

- This mod: CyclopsCore-1.12.2-0.11.8.jar
- Minecraft: 1.12.2
- Forge: 14.23.4.2747
EvilCraft-1.12.2-0.10.62.jar
UndergroundBiomesConstructs-1.12-1.2.1.jar

#### Log file:

```
java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at org.cyclops.cyclopscore.block.property.BlockPropertyManagerComponent.getStateFromMeta(BlockPropertyManagerComponent.java:191)
    at org.cyclops.cyclopscore.config.configurable.ConfigurableBlock.getStateFromMeta(ConfigurableBlock.java:37)
    at exterminatorjeff.undergroundbiomes.common.block.UBOre.<init>(UBOre.java:71)
    at exterminatorjeff.undergroundbiomes.common.block.UBOreIgneous.<init>(UBOreIgneous.java:22)
    at exterminatorjeff.undergroundbiomes.intermod.OresRegistry.registerBlocks(OresRegistry.java:121)
    at exterminatorjeff.undergroundbiomes.core.CommonProxy.registerBlocks(CommonProxy.java:243)
    at exterminatorjeff.undergroundbiomes.core.UndergroundBiomes.registerBlocks(UndergroundBiomes.java:63)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_645_UndergroundBiomes_registerBlocks_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3929)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by rubensworks** [comment]
Can you report this to UndergroundBiomes? (And link back here)

It looks like they are doing non-intended things with Dark Ore.

**Comment by LemADEC** [comment]
It's a bug in my configuration, it just happens the other mods are more tolerant with metadata = -1.
