### ISSUE TITLE
java.lang.NoSuchFieldException when I issued a plugin command /tps

### ISSUE THREAD

**Issue by Remering** [CyclopsMC/CyclopsCore#150]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Exception stacks are filled in my terminal when I issue the command `/tps`.
This also happens when I start the server. 
But it espically happends when someone issues the command `/tps`.
```
[14:48:38] [Server thread/WARN] [/]: java.lang.NoSuchFieldException: modifiers
[14:48:38] [Server thread/WARN] [/]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2489)
[14:48:38] [Server thread/WARN] [/]: 	at org.cyclops.cyclopscore.persist.nbt.NBTClassType.performActionForField(NBTClassType.java:618)
[14:48:38] [Server thread/WARN] [/]: 	at org.cyclops.cyclopscore.persist.nbt.NBTProviderComponent.readPersistedField(NBTProviderComponent.java:40)
[14:48:38] [Server thread/WARN] [/]: 	at org.cyclops.cyclopscore.persist.nbt.NBTProviderComponent.readGeneratedFieldsFromNBT(NBTProviderComponent.java:53)
[14:48:38] [Server thread/WARN] [/]: 	at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.readGeneratedFieldsFromNBT(CyclopsTileEntity.java:42)
[14:48:38] [Server thread/WARN] [/]: 	at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.read(CyclopsTileEntity.java:199)
[14:48:38] [Server thread/WARN] [/]: 	at org.cyclops.integrateddynamics.core.tileentity.TileMultipartTicking.read(TileMultipartTicking.java:127)
[14:48:38] [Server thread/WARN] [/]: 	at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.func_230337_a_(CyclopsTileEntity.java:195)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.tileentity.TileEntity.lambda$readTileEntity$1(TileEntity.java:112)
[14:48:38] [Server thread/WARN] [/]: 	at java.base/java.util.Optional.map(Optional.java:258)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.tileentity.TileEntity.func_235657_b_(TileEntity.java:110)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222650_a(ChunkSerializer.java:411)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.world.chunk.storage.ChunkSerializer.lambda$read$2(ChunkSerializer.java:130)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.world.chunk.Chunk.func_217318_w(Chunk.java:486)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.world.server.ChunkManager.lambda$null$25(ChunkManager.java:610)
[14:48:38] [Server thread/WARN] [/]: 	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
[14:48:38] [Server thread/WARN] [/]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[14:48:38] [Server thread/WARN] [/]: 	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$26(ChunkManager.java:597)
[14:48:38] [Server thread/WARN] [/]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
[14:48:38] [Server thread/WARN] [/]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:554)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:564)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(ServerChunkProvider.java:287)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:857)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:846)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:97)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:825)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:555)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:358)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:723)
[14:48:38] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276)
[14:48:38] [Server thread/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

I notice [this issue](https://github.com/CyclopsMC/CyclopsCore/issues/148) has already reported it,  but I think that one is not proper. So I issue it again.
#### Steps to reproduce the problem:

1. issue the command `/tps`

#### Expected behaviour:

____

#### Versions:

- This mod: `1.9.5`
- Minecraft: `1.16.5`
- Forge: `36.0.1`

#### Log file:
Log file is too large to paste it on the pastebin.
I upload it [here](https://github.com/Remering/pastebins/blob/main/2021-01-24-1.log).
The server crashed in this log, but never mind,  it's my fault.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Looks like the same problem as #148.
