### ISSUE TITLE
Config crash

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/CyclopsCore#189]
#### Issue type:

- :bug: Bug 

____

#### Short description:

```
[26Jul2024 17:15:20.817] [Render thread/ERROR] [net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl/]: Failed to handle packet net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket@45126fae
java.lang.NullPointerException: Cannot invoke "org.cyclops.cyclopscore.init.ModBase.getConfigHandler()" because "mod" is null
    at TRANSFORMER/cyclopscore@1.19.7/org.cyclops.cyclopscore.infobook.condition.ConfigSectionConditionHandler.isSatisfied(ConfigSectionConditionHandler.java:28) ~[CyclopsCore-1.21-neoforge-1.19.7.jar%23222!/:1.19.7]
    at TRANSFORMER/cyclopscore@1.19.7/org.cyclops.cyclopscore.infobook.InfoBookParser.buildSection(InfoBookParser.java:625) ~[CyclopsCore-1.21-neoforge-1.19.7.jar%23222!/:1.19.7]
    at TRANSFORMER/cyclopscore@1.19.7/org.cyclops.cyclopscore.infobook.InfoBookParser.buildSection(InfoBookParser.java:601) ~[CyclopsCore-1.21-neoforge-1.19.7.jar%23222!/:1.19.7]
    at TRANSFORMER/cyclopscore@1.19.7/org.cyclops.cyclopscore.infobook.InfoBookParser.buildSection(InfoBookParser.java:601) ~[CyclopsCore-1.21-neoforge-1.19.7.jar%23222!/:1.19.7]
    at TRANSFORMER/cyclopscore@1.19.7/org.cyclops.cyclopscore.infobook.InfoBookParser.initializeInfoBook(InfoBookParser.java:564) ~[CyclopsCore-1.21-neoforge-1.19.7.jar%23222!/:1.19.7]
    at TRANSFORMER/cyclopscore@1.19.7/org.cyclops.cyclopscore.infobook.InfoBookRegistry.afterRecipesAndTagsLoaded(InfoBookRegistry.java:127) ~[CyclopsCore-1.21-neoforge-1.19.7.jar%23222!/:1.19.7]
    at TRANSFORMER/cyclopscore@1.19.7/org.cyclops.cyclopscore.infobook.InfoBookRegistry.onClientRecipesLoaded(InfoBookRegistry.java:99) ~[CyclopsCore-1.21-neoforge-1.19.7.jar%23222!/:1.19.7]
    at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.1.jar%23106!/:?]
    at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%23106!/:?]
    at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%23106!/:?]
    at TRANSFORMER/neoforge@21.0.133-beta/net.neoforged.neoforge.client.ClientHooks.onRecipesUpdated(ClientHooks.java:658) ~[neoforge-21.0.133-beta-universal.jar%23184!/:?]
```

____

#### Versions:

- This mod: 
- Minecraft: 1.21
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
New crash after last change:

```
---- Minecraft Network Protocol Error Report ----
// Sabotage!

Time: 2024-07-28 19:50:30
Description: Packet handling error

java.lang.IllegalArgumentException: The mod integratedterminals could not be found as ModBase.
at TRANSFORMER/cyclopscore@1.19.8/org.cyclops.cyclopscore.infobook.InfoBookParser.buildSection(InfoBookParser.java:622) ~[CyclopsCore-1.21-neoforge-1.19.8.jar%23224!/:1.19.8] {re:classloading}
at TRANSFORMER/cyclopscore@1.19.8/org.cyclops.cyclopscore.infobook.InfoBookParser.buildSection(InfoBookParser.java:601) ~[CyclopsCore-1.21-neoforge-1.19.8.jar%23224!/:1.19.8] {re:classloading}
at TRANSFORMER/cyclopscore@1.19.8/org.cyclops.cyclopscore.infobook.InfoBookParser.buildSection(InfoBookParser.java:601) ~[CyclopsCore-1.21-neoforge-1.19.8.jar%23224!/:1.19.8] {re:classloading}
at TRANSFORMER/cyclopscore@1.19.8/org.cyclops.cyclopscore.infobook.InfoBookParser.initializeInfoBook(InfoBookParser.java:564) ~[CyclopsCore-1.21-neoforge-1.19.8.jar%23224!/:1.19.8] {re:classloading}
at TRANSFORMER/cyclopscore@1.19.8/org.cyclops.cyclopscore.infobook.InfoBookRegistry.afterRecipesAndTagsLoaded(InfoBookRegistry.java:127) ~[CyclopsCore-1.21-neoforge-1.19.8.jar%23224!/:1.19.8] {re:classloading}
at TRANSFORMER/cyclopscore@1.19.8/org.cyclops.cyclopscore.infobook.InfoBookRegistry.onClientRecipesLoaded(InfoBookRegistry.java:99) ~[CyclopsCore-1.21-neoforge-1.19.8.jar%23224!/:1.19.8] {re:classloading}
at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.1.jar%23120!/:?] {}
at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%23120!/:?] {}
at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%23120!/:?] {}
at TRANSFORMER/neoforge@21.0.143/net.neoforged.neoforge.client.ClientHooks.onRecipesUpdated(ClientHooks.java:658) ~[neoforge-21.0.143-universal.jar%23183!/:?] {re:classloading}
at TRANSFORMER/minecraft@1.21/net.minecraft.client.multiplayer.ClientPacketListener.handleUpdateRecipes(ClientPacketListener.java:1500) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chat_heads.mixins.json:ClientPacketListenerMixin from mod chat_heads,pl:mixin:APP:crafttweaker.mixins.json:client.transform.multiplayer.MixinClientPacketListener from mod crafttweaker,pl:mixin:APP:ftbchunks-common.mixins.json:ClientPacketListenerMixin from mod ftbchunks,pl:mixin:APP:creeperoverhaul-common.mixins.json:ClientPacketListenerMixin from mod creeperoverhaul,pl:mixin:APP:the_bumblezone-common.mixins.json:client.ClientPacketListenerMixin from mod the_bumblezone,pl:mixin:A,pl:runtimedistcleaner:A}
at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.handle(ClientboundUpdateRecipesPacket.java:32) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:classloading}
at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.handle(ClientboundUpdateRecipesPacket.java:13) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:classloading}
at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:classloading}
at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,re:computing_frames,re:classloading}
at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.runTick(Minecraft.java:1155) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:emojiful.mixins.json:MinecraftEmojifulMixin from mod emojiful,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin from mod the_bumblezone,pl:mixin:APP:bigshot.mixins.json:MixinMinecraft from mod bigshot,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:ichunutil.mixins.json:client.MinecraftMixin from mod ichunutil,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:armorposer.neoforge.mixins.json:MinecraftMixin from mod armorposer,pl:mixin:A,pl:runtimedistcleaner:A}
at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:emojiful.mixins.json:MinecraftEmojifulMixin from mod emojiful,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin from mod the_bumblezone,pl:mixin:APP:bigshot.mixins.json:MixinMinecraft from mod bigshot,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:ichunutil.mixins.json:client.MinecraftMixin from mod ichunutil,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:armorposer.neoforge.mixins.json:MinecraftMixin from mod armorposer,pl:mixin:A,pl:runtimedistcleaner:A}
at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:classloading,pl:runtimedistcleaner:A}
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.21.jar%23101!/:4.0] {}
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.21.jar%23101!/:4.0] {}
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.21.jar%23101!/:4.0] {}
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.21.jar%23101!/:4.0] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23117!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23117!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23117!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23117!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23117!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23117!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23117!/:?] {}
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
at TRANSFORMER/cyclopscore@1.19.8/org.cyclops.cyclopscore.infobook.InfoBookParser.buildSection(InfoBookParser.java:622) ~[CyclopsCore-1.21-neoforge-1.19.8.jar%23224!/:1.19.8] {re:classloading}
at TRANSFORMER/cyclopscore@1.19.8/org.cyclops.cyclopscore.infobook.InfoBookParser.buildSection(InfoBookParser.java:601) ~[CyclopsCore-1.21-neoforge-1.19.8.jar%23224!/:1.19.8] {re:classloading}
at TRANSFORMER/cyclopscore@1.19.8/org.cyclops.cyclopscore.infobook.InfoBookParser.buildSection(InfoBookParser.java:601) ~[CyclopsCore-1.21-neoforge-1.19.8.jar%23224!/:1.19.8] {re:classloading}
at TRANSFORMER/cyclopscore@1.19.8/org.cyclops.cyclopscore.infobook.InfoBookParser.initializeInfoBook(InfoBookParser.java:564) ~[CyclopsCore-1.21-neoforge-1.19.8.jar%23224!/:1.19.8] {re:classloading}
at TRANSFORMER/cyclopscore@1.19.8/org.cyclops.cyclopscore.infobook.InfoBookRegistry.afterRecipesAndTagsLoaded(InfoBookRegistry.java:127) ~[CyclopsCore-1.21-neoforge-1.19.8.jar%23224!/:1.19.8] {re:classloading}
at TRANSFORMER/cyclopscore@1.19.8/org.cyclops.cyclopscore.infobook.InfoBookRegistry.onClientRecipesLoaded(InfoBookRegistry.java:99) ~[CyclopsCore-1.21-neoforge-1.19.8.jar%23224!/:1.19.8] {re:classloading}
at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.1.jar%23120!/:?] {}
at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%23120!/:?] {}
at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%23120!/:?] {}
at TRANSFORMER/neoforge@21.0.143/net.neoforged.neoforge.client.ClientHooks.onRecipesUpdated(ClientHooks.java:658) ~[neoforge-21.0.143-universal.jar%23183!/:?] {re:classloading}
-- Incoming Packet --
Details:
Type: clientbound/minecraft:update_recipes
Is Terminal: false
Is Skippable: false
Stacktrace:
at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.PacketUtils.fillCrashReport(PacketUtils.java:56) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:classloading}
at TRANSFORMER/minecraft@1.21/net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl.storeDisconnectionReport(ClientCommonPacketListenerImpl.java:130) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
at TRANSFORMER/minecraft@1.21/net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl.onPacketError(ClientCommonPacketListenerImpl.java:114) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:32) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:classloading}
at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,re:computing_frames,re:classloading}
at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.runTick(Minecraft.java:1155) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:emojiful.mixins.json:MinecraftEmojifulMixin from mod emojiful,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin from mod the_bumblezone,pl:mixin:APP:bigshot.mixins.json:MixinMinecraft from mod bigshot,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:ichunutil.mixins.json:client.MinecraftMixin from mod ichunutil,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:armorposer.neoforge.mixins.json:MinecraftMixin from mod armorposer,pl:mixin:A,pl:runtimedistcleaner:A}
at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:emojiful.mixins.json:MinecraftEmojifulMixin from mod emojiful,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin from mod the_bumblezone,pl:mixin:APP:bigshot.mixins.json:MixinMinecraft from mod bigshot,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:ichunutil.mixins.json:client.MinecraftMixin from mod ichunutil,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:armorposer.neoforge.mixins.json:MinecraftMixin from mod armorposer,pl:mixin:A,pl:runtimedistcleaner:A}
at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21-20240613.152323-srg.jar%23182!/:?] {re:classloading,pl:runtimedistcleaner:A}
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.21.jar%23101!/:4.0] {}
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.21.jar%23101!/:4.0] {}
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.21.jar%23101!/:4.0] {}
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.21.jar%23101!/:4.0] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23117!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23117!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23117!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23117!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23117!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23117!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23117!/:?] {}
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}


-- Connection --
Details:
Protocol: play
Flow: CLIENTBOUND
Server type: OTHER... (4 KB left)
```
