### ISSUE TITLE
Neoforge 1.21 Config Crash

### ISSUE THREAD

**Issue by Saereth** [CyclopsMC/CyclopsCore#190]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When updating Flopper and Cyclopse core to latest the pack no longer launches with the following error:

```
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Cannot get config value before config is loaded.

```

https://mclo.gs/ApoHSVV

#### Steps to reproduce the problem:

Currently Working:
CyclopsCore-1.21.1-neoforge-1.19.11.jar 
Flopper-1.21-neoforge-1.1.5.jar

Whenever I update to these versions it no longer loads/crashes:
cyclopscore-1.21.1-neoforge-1.20.0-570.jar
flopper-1.21.1-neoforge-1.1.6-139.jar

#### Expected behaviour:

I would expect to to load as normal
____

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Since the crashlog doesn't mention CC or Flopper, I don't see yet how this is connected. (it seems to be SimpleWeather triggering the problem)
Could you share your full NeoForge logs? There might be something else in there.

**Comment by Saereth** [comment]
This is a pretty common issue with neoforge mods these days, its misreported in the log, but yeah the debug log shows it better. 
https://mclo.gs/DMc0cCk

You can see around line 13276 all of the cyclopscore reliant mods fail to load with the newer version

Revelant exerpt:
```

[net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: integratedterminals, class org.cyclops.integratedterminals.IntegratedTerminals
java.lang.NullPointerException: Cannot invoke "org.cyclops.cyclopscore.init.IModBase.getModHelpers()" because "org.cyclops.cyclopscore.helper.CyclopsCoreInstance.MOD" is null
	at TRANSFORMER/cyclopscore@1.20.0/org.cyclops.cyclopscore.helper.IModHelpers.get(IModHelpers.java:12) ~[cyclopscore-1.21.1-neoforge-1.20.0-570.jar%23532!/:1.20.0-570]
	at TRANSFORMER/cyclopscore@1.20.0/org.cyclops.cyclopscore.helper.MinecraftHelpers.isClientSide(MinecraftHelpers.java:130) ~[cyclopscore-1.21.1-neoforge-1.20.0-570.jar%23532!/:1.20.0-570]
	at TRANSFORMER/cyclopscore@1.20.0/org.cyclops.cyclopscore.init.ModBase.<init>(ModBase.java:95) ~[cyclopscore-1.21.1-neoforge-1.20.0-570.jar%23532!/:1.20.0-570]
	at TRANSFORMER/cyclopscore@1.20.0/org.cyclops.cyclopscore.init.ModBaseVersionable.<init>(ModBaseVersionable.java:22) ~[cyclopscore-1.21.1-neoforge-1.20.0-570.jar%23532!/:1.20.0-570]
	at TRANSFORMER/integratedterminals@1.5.1/org.cyclops.integratedterminals.IntegratedTerminals.<init>(IntegratedTerminals.java:60) ~[IntegratedTerminals-1.21.1-neoforge-1.5.1.jar%23598!/:1.5.1]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.24.jar%23106!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.24.jar%23106!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.24.jar%23106!/:4.0]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
[20Aug2024 01:04:28.886] [modloading-worker-0/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: integratedterminalscompat, class org.c
``` 

Only these 2 mods seem impacted, and flopper may be unrelated but I cant update it without the new cyclopscore to test, it also works fine on the older version
<img width="319" alt="image" src="https://github.com/user-attachments/assets/ecdb7bc2-5791-4241-9565-e47fe0a4546d">

**Comment by rubensworks** [comment]
Aha, that's the stacktrace I need indeed, thanks!

**Comment by rubensworks** [comment]
Note to self: Use `getModHelpers()` instead of `MinecraftHelpers` on https://github.com/CyclopsMC/CyclopsCore/blob/master-1.21/loader-neoforge/src/main/java/org/cyclops/cyclopscore/init/ModBase.java#L95C9-L95C47

<blockquote><img src="https://opengraph.githubassets.com/1a6f7f7a6d954ae086f40e3f3f741d5b39c452c5df5958d6516a4b8fb443ae45/CyclopsMC/CyclopsCore" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore/blob/master-1.21/loader-neoforge/src/main/java/org/cyclops/cyclopscore/init/ModBase.java">CyclopsCore/loader-neoforge/src/main/java/org/cyclops/cyclopscore/init/ModBase.java at master-1.21 · CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsMC/CyclopsCore</div></blockquote>

**Comment by rubensworks** [comment]
For reference, this was caused by some refactoring changes due to my recent addition of multiloader support.
