### ISSUE TITLE
Could not access field during tile persistence

### ISSUE THREAD

**Issue by Gunner76th** [CyclopsMC/CyclopsCore#33]
http://pastebin.com/xZcmfLCt
Player was crafting leather and server crashed. Running Sky Factory 3 from FTB using the official Server and client packs with no modifications to the pack setup.

**Comment by Gunner76th** [comment]
Looks like this is actually being caused by Integrated Dynamics as posted here https://github.com/CyclopsMC/IntegratedDynamics/issues/100

**Comment by rubensworks** [comment]
@Gunner76th I can't look into it right now myself, but in the meantime, could you try the following dev build?
This won't fix your issue, but it will add additional information to the logs which may help me pinpoint the problem.
https://dl.bintray.com/cyclopsmc/dev/org/cyclops/cyclopscore/CyclopsCore/1.9.4-0.8.2-450/CyclopsCore-1.9.4-0.8.2-450.jar

**Comment by Gunner76th** [comment]
I am not sure what changes you made to dev build 450, however you need to push that change to Release build 0.8.3 as it has resolved the crash related to using the drying basin to process rotten flesh into leather. One of my Devs from Team IHOC will be posting shortly what he was doing on his end when testing your Dev build 450. 

Because the server did not crash, and there was nothing at all posted to the console when he was testing, there is nothing I can send you that would be of any assistance. I am having him test all other items in the drying basin to see if any of them manage to crash the server.

**Comment by rubensworks** [comment]
That's strange, because there literally have been no changes that could solve this, only some additional debugging.
Did some other mods update as well? Because I have the feeling that there may be a coremod causing this.

**Comment by Gunner76th** [comment]
Ok it didnt crash the server, however Meril Resin did just cause the console to spam a bunch of information

**Comment by rubensworks** [comment]
Ok, that's probably good, I need that information.

**Comment by Gunner76th** [comment]
I will be uploading our complete console log set shortly. here is a snipet of the current console spammage

 [11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: java.lang.IllegalAccessException: Class org.cyclops.cyclopscore.persist.nbt.NBTClassType can not access a member of class org.cyclops.integrateddynamics.tileentity.TileDryingBasin with modifiers "private"
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at java.lang.reflect.Field.get(Field.java:390)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at org.cyclops.cyclopscore.persist.nbt.NBTClassType.persistedFieldAction(NBTClassType.java:628)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at org.cyclops.cyclopscore.persist.nbt.NBTClassType.performActionForField(NBTClassType.java:602)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at org.cyclops.cyclopscore.persist.nbt.NBTProviderComponent.writePersistedField(NBTProviderComponent.java:36)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at org.cyclops.cyclopscore.persist.nbt.NBTProviderComponent.writeGeneratedFieldsToNBT(NBTProviderComponent.java:46)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.writeGeneratedFieldsToNBT(CyclopsTileEntity.java:45)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.func_189515_b(CyclopsTileEntity.java:192)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at org.cyclops.cyclopscore.tileentity.InventoryTileEntityBase.func_189515_b(InventoryTileEntityBase.java:171)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at org.cyclops.cyclopscore.tileentity.TankInventoryTileEntity.func_189515_b(TankInventoryTileEntity.java:130)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at mcp.mobius.waila.addons.capability.HUDHandlerEnergy.getNBTData(HUDHandlerEnergy.java:43)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at mcp.mobius.waila.network.Message0x01TERequest.channelRead0(Message0x01TERequest.java:117)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at mcp.mobius.waila.network.Message0x01TERequest.channelRead0(Message0x01TERequest.java:29)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:100)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleServerSideCustomPacket(NetworkDispatcher.java:446)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:269)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:73)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[11:15:14] [Netty Epoll Server IO #2/INFO] [STDERR/]: [org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:604]: 	at java.lang.Thread.run(Thread.java:745)
[11:15:44] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[11:16:29] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[11:17:14] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world

**Comment by Gunner76th** [comment]
Sorry for the spam wall. I tried to use the spoiler tag but it didnt work.

**Comment by Gunner76th** [comment]
Also, no since lastnight when I first posted this, as well as replied to the post on the Integrated Dynamics github, none of our mods on the server or client have been updated or changed. the only one that has been touched is the core mod you are having me test.

**Comment by Gunner76th** [comment]
https://cdn.discordapp.com/attachments/185154175200526336/265876300705693697/2017-01-03_17.17.35.png this is a screen grab my DEV did when he was testing the Meril Resin that generated the above information.

**Comment by Gunner76th** [comment]
I am having him redo the test, and this time mention in game what each combo is that he is testing before he does it, so that you can see in the log file what triggers the console spam and what doesnt

**Comment by Gunner76th** [comment]
[Log files Dev 450.zip](https://github.com/CyclopsMC/CyclopsCore/files/682720/Log.files.Dev.450.zip)

**Comment by Gunner76th** [comment]
That is all of the log files for our testing. Hopefully this helps. Because the dev build has stopped the server from crashing (even if it does spam the console on Meril) I am considering this issue resolved in DEV build. I am going to keep the dev build on our server until you are able to push it to the release channel. I will also update/cross post in Integrated Dynamics our results here.

**Comment by rubensworks** [comment]
@Gunner76th Could you try the following dev build and let me know if you still experience the console spam? https://dl.bintray.com/cyclopsmc/dev/org/cyclops/cyclopscore/CyclopsCore/1.9.4-0.8.2-459/CyclopsCore-1.9.4-0.8.2-459.jar

**Comment by Gunner76th** [comment]
Beginning test now. Using Dev Build 459 we have tried everything, and there is no output to the console now.

**Comment by rubensworks** [comment]
Ok, that's good new. That means there is some mod in your pack doing some funky things it shouldn't be doing. But if that latest change resolves the issue, I can circumvent it.
Thanks for testing this!

**Comment by Gunner76th** [comment]
No problem. The modpack in question is maintained by Bacon_Donut, and is SkyFactory 3 which was released about 24-48 hours ago.
