### ISSUE TITLE
NPE when searching the word "fluid" in JEI

### ISSUE THREAD

**Issue by Lothrazar** [CyclopsMC/CyclopsCore#59]
Might be fault of JEI, not sure exactly.   

https://pastebin.com/sSgL8ACR

java.lang.NullPointerException: Rendering ingredient
	at org.cyclops.cyclopscore.client.model.DynamicBaseModel.addColoredBakedQuad(DynamicBaseModel.java:145)
	at org.cyclops.fluidconverters.client.model.ModelFluidConverter.getGeneralQuads(ModelFluidConverter.java:85)
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.func_188616_a(DynamicItemAndBlockModel.java:50)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:122)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at mezz.jei.render.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:139)
	at mezz.jei.render.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:112)
	at mezz.jei.render.GuiIngredientFastList.render(GuiIngredientFastList.java:169)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:141)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:174)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:74)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_714_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:616)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1115)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by rubensworks** [comment]
Looks like a Fluid Converters crash, perhaps an invalid Fluid registration, will have to add some additional checks for that.
